[phases.setup]
nixPkgs = ["nodejs_18", "python39"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps",
  "pip install -r requirements.txt --user"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT"
